package:
  name: fsttrpgprimarystats
  version: 0.1.1

build:
 number: 1
 string: alpha

source:
  git_url: https://github.com/Krypticdator/FSTTRPGPrimaryStats.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: Fuzion Roleplayin System primary stats